### ISSUE TITLE
SQL fails in the very beginning

### ISSUE THREAD

**Issue by yurivict** [jansmolders86/mediacenterjs#216]
```
Executing (default): SELECT COUNT(id) ct FROM SequelizeMeta
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: SequelizeMeta
    at Query.formatError (/usr/ports/multimedia/mediacenterjs/work/stage/usr/local/share/node-projects/mediacenterjs/node_modules/sequelize/lib/dialects/sqlite/query.js:328:14)                                                                                                                                                                        
    at afterExecute (/usr/ports/multimedia/mediacenterjs/work/stage/usr/local/share/node-projects/mediacenterjs/node_modules/sequelize/lib/dialects/sqlite/query.js:100:29) 
    at replacement (/usr/ports/multimedia/mediacenterjs/work/stage/usr/local/share/node-projects/mediacenterjs/node_modules/sqlite3/lib/trace.js:20:31)                     
    at Statement.errBack (/usr/ports/multimedia/mediacenterjs/work/stage/usr/local/share/node-projects/mediacenterjs/node_modules/sqlite3/lib/sqlite3.js:16:21)             

Executing (c3d17461-5983-42ac-aca1-6cbaef99b2fc): BEGIN TRANSACTION;
Executing (c3d17461-5983-42ac-aca1-6cbaef99b2fc): -- SQLite is not able to choose the isolation level REPEATABLE READ.
Executing (c3d17461-5983-42ac-aca1-6cbaef99b2fc): -- SQLite does not support SET autocommit.
Executing (c3d17461-5983-42ac-aca1-6cbaef99b2fc): SELECT `id`, `deviceID`, `lastSeen`, `isAllowed` FROM `Devices` AS `Device` WHERE `Device`.`deviceID` = 'ubuntu_::1' LIMIT 1;
```

Change of port doesn't take effect (nobody listens on it).

**Comment by jansmolders86** [comment]
I just pushed a fix, defining sqlite in the code solved this issue. Should your sqlite module be acting up, please run:  npm install sqlite --build-from-source

**Comment by omgbox** [comment]
this > npm install sqlite --build-from-source

does not fix it

**Comment by jansmolders86** [comment]
on windows download the exe from the website mediacenterjs.com.  On Linux this issue should be fixed.

**Comment by Skruf90** [comment]
Same issue after trying the npm install sqlite --build-from-source command.

**Comment by jansmolders86** [comment]
I fixed the issue for real this time :), Would you mind updating and checking again? Thanks!
